# Generated by Django 5.2.13 on 2026-04-13 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Run', max_length=200)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('threads', models.CharField(max_length=100)),
                ('runs', models.PositiveIntegerField(default=5)),
                ('extra_args', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stdout_text', models.TextField(blank=True)),
                ('stderr_text', models.TextField(blank=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='results/csv/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='results/reports/')),
                ('runtime_plot', models.ImageField(blank=True, null=True, upload_to='results/plots/')),
                ('speedup_plot', models.ImageField(blank=True, null=True, upload_to='results/plots/')),
                ('efficiency_plot', models.ImageField(blank=True, null=True, upload_to='results/plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
