# Generated by Django 5.2.13 on 2026-05-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='paradigm',
            field=models.CharField(choices=[('openmp', 'OpenMP'), ('mpi', 'MPI'), ('pthreads', 'pthreads')], default='openmp', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='projected_efficiency_plot',
            field=models.ImageField(blank=True, null=True, upload_to='results/plots/'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='projected_runtime_plot',
            field=models.ImageField(blank=True, null=True, upload_to='results/plots/'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='projected_speedup_plot',
            field=models.ImageField(blank=True, null=True, upload_to='results/plots/'),
        ),
    ]
